export const AJOUTER_INGREDIENT = "AJOUTER_INGREDIENT";

export const SUPPRIMER_INGREDINET = "SUPPRIMER_INGREDINET";

export const MODIFIER_INGREDIENT = "MODIFIER_INGREDIENT";

export const AJOUTER_RECETTE = "AJOUTER_RECETTE";

export const SUPPRIMER_ROCETTE = "SUPPRIMER_ROCETTE";

export const MODIFIER_RECETTE = "MODIFIER_RECETTE";
