export const MAKE_REQUEST = "MAKE_REQUEST";
export const FAIL_REQUEST = "FAIL_REQUEST";
export const FETCH_CLIENTS_REQUEST = "FETCH_CLIENTS_REQUEST";

export const DELETE_CLIENT = "DELETE_CLIENT";

export const ADD_CLIENT = "ADD_CLIENT";

export const GET_SINGLE_CLIENT = "GET_SINGLE_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
