export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const CHERCHER_INGREDIENT = "CHERCHER_INGREDIENT";
export const DECREMENTER_NOTE_COMMENTAIRE = "DECREMENTER_NOTE_COMMENTAIRE";
export const DETAIL_ROPAS = "DETAIL_ROPAS";
export const AJOUTER_ROPA = "AJOUTER_ROPA";
export const AJOUTER_COMMENTAIRE = "AJOUTER_COMMENTAIRE";
export const FILTRE_CUISINE = "FILTRE_CUISINE";
export const CHERCHER_NOM = "CHERCHER_NOM";
